- name: create ec2 instance and update route53 records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0f110578dbed67965
    zone_id: Z00363011Z6DCTPYPRFG8
    domain_name: daws89s.fun
    instances:
    - mongodb

  tasks:
  - name: create a ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: print private ip address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print public  ip address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].public_ip_address}}"
    loop: "{{ ec2_output.results}}"

  - name: update route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item}}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
    overwrite: true
    
  



