- name: setup payment server  
  hosts: payment
  become: yes
  tasks:
  - name: install python libreis
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: 