- name: setup shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.package:
      name: maven
      state: present
    
  - name: create a system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      shell: /sbin/nologin
      home: /app

# if it is /app directory exist it will remove when running second time
  - name: remove directory
    ansible.builtin.file:
        path: /app
        state: absent

  - name: create a /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: remove shiiping application 
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: downloade the shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: unachive the shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy shipping.service 
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: restart shipping service
    ansible.builtin.systemd_service:
      name: shipping
      daemon_reload: true
      enabled: yes
      state: started
      

  - name: install mysql client
    ansible.builtin.package:
      name: mysql 
      state: present

  - name: install mysql python libreis
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{item}}"
    loop:
    - PyMySQL
    - cryptography

  - name: import the shipping data to mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.daws89s.fun
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql 

    
  - name: restart shiping service
    ansible.builtin.service:
      name: shipping
      state: restarted