- name: setup user server
  hosts: user
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      shell: /sbin/nologin
      home: /app

# remove /app directory if it is exist while running 2nd time
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: craete a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: downloade user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: unachive user application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app/

  - name: copy the user.service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  
  - name: restrt user and enable user
    ansible.builtin.systemd_service: 
      name: user
      state: started
      enabled: true
      daemon_reload: true

